<?php

include("include/all.php");

$panthera->connect();


if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') {
    //do nothing, HTTP 200
    exit();
}
    
// DO NOT require_logged_user_JWT();

if ($_SERVER['REQUEST_METHOD'] === 'GET') {

$panthera->execute_update("SET ANSI_WARNINGS  OFF");

/*
$query = "SELECT U.ID_UBICAZIONE,
U.ID_MAGAZZINO,
U.R_UTENTE_AGG,
U.TIMESTAMP_AGG,
S.ID_ARTICOLO,
A.DESCRIZIONE,
A.DISEGNO,
A.R_UM_PRM_MAG,
S.ID_COMMESSA,
S.QTA_GIAC_PRM FROM THIP.UBICAZIONI_LL U JOIN 
THIPPERS.YUBICAZIONI_LL YU ON U.ID_AZIENDA=YU.ID_AZIENDA 
AND U.ID_UBICAZIONE=YU.ID_UBICAZIONE 
AND U.ID_MAGAZZINO=YU.ID_MAGAZZINO JOIN THIP.SALDI_UBICAZIONE_V01 S ON U.ID_AZIENDA=S.ID_AZIENDA 
AND U.ID_UBICAZIONE=S.ID_UBICAZIONE AND 
U.ID_MAGAZZINO=S.ID_MAGAZZINO JOIN THIP.ARTICOLI A ON S.ID_AZIENDA=A.ID_AZIENDA AND 
S.ID_ARTICOLO=A.ID_ARTICOLO WHERE  
S.QTA_GIAC_PRM < 0 
ORDER BY S.ID_ARTICOLO";

$query="select COUNT(*) FROM THIP.DOC_TRA_TES T
          WHERE T.ID_AZIENDA='001'
          AND T.STATO = 'V' AND T.STATO_AVANZAMENTO='1'
          AND T.R_CAU_DOC_TRA IN ('T01','T02')
          AND EXISTS( SELECT 1 FROM THIP.DOC_TRA_RIG R
          WHERE R.ID_AZIENDA=T.ID_AZIENDA AND R.ID_ANNO_DOC=T.ID_ANNO_DOC AND R.ID_NUMERO_DOC=T.ID_NUMERO_DOC)       
          ";
$query="SELECT * FROM THIP.CM_DOC_TRA_TES T
                WHERE T.ID_AZIENDA='001'
                AND T.STATO = 'V' 
                AND T.STATO_AVANZAMENTO='1'
                AND T.R_CAU_DOC_TRA IN ('T01','T02')
                AND EXISTS( SELECT 1 FROM THIP.CM_DOC_TRA_RIG R
                WHERE R.ID_AZIENDA=T.ID_AZIENDA AND R.ID_ANNO_DOC=T.ID_ANNO_DOC AND R.ID_NUMERO_DOC=T.ID_NUMERO_DOC AND R.STATO= 'V' AND R.STATO_AVANZAMENTO='1')";
                AND S.ID_ARTICOLO='ASD' AND S.ID_COMMESSA='all'
*/
$query = "SELECT * FROM THERA.BATCH_JOB WHERE STATUS = 'A' AND SCHEDULED_JOB_ID = 'CMDocTrasf'";

                
$result = $panthera->select_list($query);

/* 
UBICAZIONE QUERY
$query = "SELECT TOP 10 U.* FROM THIP.UBICAZIONI_LL U JOIN THIPPERS.YUBICAZIONI_LL YU ON U.ID_AZIENDA=YU.ID_AZIENDA AND U.ID_UBICAZIONE=YU.ID_UBICAZIONE AND U.ID_MAGAZZINO=YU.ID_MAGAZZINO where U.ID_AZIENDA = '001'";
*/	
  //header('Content-Type: application/json');
  //echo json_encode(['data' => $result]);
	echo "<html>" . print_query_html($result) . "</html>";

} else {
    //==========================================================
    print_error(400, "Unsupported method in request: " . $_SERVER['REQUEST_METHOD']);
}

?>